/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.GerenciadorInterGrafica;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Paulo
 */

public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCad = new javax.swing.JMenu();
        cadCliente = new javax.swing.JMenuItem();
        cadPedido = new javax.swing.JMenuItem();
        mnuCadFabricante = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cadSair = new javax.swing.JMenuItem();
        mnuPesquisar = new javax.swing.JMenu();
        mnuPesqCli = new javax.swing.JMenuItem();
        mnuPesquisaFab = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/users.png"))); // NOI18N
        mnuCad.setText("Cadastro");
        mnuCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadActionPerformed(evt);
            }
        });

        cadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/user.png"))); // NOI18N
        cadCliente.setText("Cliente");
        cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteActionPerformed(evt);
            }
        });
        mnuCad.add(cadCliente);

        cadPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/shopping_cart.png"))); // NOI18N
        cadPedido.setText("Pedido");
        cadPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPedidoActionPerformed(evt);
            }
        });
        mnuCad.add(cadPedido);

        mnuCadFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/process.png"))); // NOI18N
        mnuCadFabricante.setText("Fabricante");
        mnuCadFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadFabricanteActionPerformed(evt);
            }
        });
        mnuCad.add(mnuCadFabricante);
        mnuCad.add(jSeparator1);

        cadSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/remove.png"))); // NOI18N
        cadSair.setText("Sair");
        cadSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSairActionPerformed(evt);
            }
        });
        mnuCad.add(cadSair);

        jMenuBar1.add(mnuCad);

        mnuPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/database_search.png"))); // NOI18N
        mnuPesquisar.setText("Pesquisar");

        mnuPesqCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/user.png"))); // NOI18N
        mnuPesqCli.setText("Cliente");
        mnuPesqCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesqCliActionPerformed(evt);
            }
        });
        mnuPesquisar.add(mnuPesqCli);

        mnuPesquisaFab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/process.png"))); // NOI18N
        mnuPesquisaFab.setText("Fabricante");
        mnuPesquisaFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesquisaFabActionPerformed(evt);
            }
        });
        mnuPesquisar.add(mnuPesquisaFab);

        jMenuBar1.add(mnuPesquisar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteActionPerformed
        GerenciadorInterGrafica.getMyInstance().abrirCadastroCliente();
    }//GEN-LAST:event_cadClienteActionPerformed

    private void cadPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPedidoActionPerformed
        GerenciadorInterGrafica.getMyInstance().abrirCadastroPedido();
    }//GEN-LAST:event_cadPedidoActionPerformed

    private void cadSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadSairActionPerformed
        dispose();
    }//GEN-LAST:event_cadSairActionPerformed

    private void mnuCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadActionPerformed

    }//GEN-LAST:event_mnuCadActionPerformed

    private void mnuCadFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadFabricanteActionPerformed
        GerenciadorInterGrafica.getMyInstance().abrirCadastroFabricante();
    }//GEN-LAST:event_mnuCadFabricanteActionPerformed

    private void mnuPesqCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesqCliActionPerformed
        GerenciadorInterGrafica.getMyInstance().abrirPesqCliente();
    }//GEN-LAST:event_mnuPesqCliActionPerformed

    private void mnuPesquisaFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesquisaFabActionPerformed
        GerenciadorInterGrafica.getMyInstance().abrirPesqFabricante();
    }//GEN-LAST:event_mnuPesquisaFabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadCliente;
    private javax.swing.JMenuItem cadPedido;
    private javax.swing.JMenuItem cadSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnuCad;
    private javax.swing.JMenuItem mnuCadFabricante;
    private javax.swing.JMenuItem mnuPesqCli;
    private javax.swing.JMenuItem mnuPesquisaFab;
    private javax.swing.JMenu mnuPesquisar;
    // End of variables declaration//GEN-END:variables
}
